export default [
    {
        category: 'Art Limpieza',
        items: [
            'Toallitas',
            'Shampoo',
            'Dedenredante',
            'Jabon De Tocador',
            'Dentifrico',
            'Alcohol',
            'Isopos',
            'Desodorante',
            'Algodon',
            'Quitaesmalte',
            'Desmaquillante',
            'Rollo De Cocina',
            'Bolsas De Residuos',
            'Esponja Virulana',
            'Papel Higienico',
            'Lavandina',
            'Jabon Lavarropas',
            'Detergente',
            'Perfumina',
            'Cif',
            'Limpiavidrios',
            'Lustramuebles',
            'Fosforos',
            'Guantes',
            'Trapo De Piso',
            'Trapo Balerina',
            'Desodorante De Ambiente',
        ],
    },
    {
        category: 'Almacen',
        items: [
            'Te / Boldo',
            'Mate',
            'Yerba',
            'Galletitas De Agua',
            'Leche',
            'Flan Postre',
            'Chocolatada',
            'Azucar Impalpable',
            'Maicena',
            'Edulcorante',
            'Azucar',
            'Cafe / Saquitos',
            'Galletitas Dulces',
            'Verdura Congelada',
            'Patitas',
            'Aceite Girasol / Oliva',
            'Vinagre / Limon',
            'Dulce De Lece',
            'Sal Fina / Entrefina',
            'Harina',
            'Polenta',
            'Lentejas',
            'Fideos Largos / Sopa',
            'Capeletinis',
            'Caldos',
            'Avena',
            'Arroz',
            'Sopa',
            'Mermelada',
        ],
    },
    {
        category: 'Enlatados',
        items: [
            'Acelga Chauchas',
            'Soja Lentejas',
            'Garbanzos',
            'Remolacha',
            'Atun Caballa',
            'Mayonesa',
            'Savora Salsa Golf',
            'Tomates',
            'Morrones',
            'Palmitos',
            'Duraznos Anana',
            'Champignones',
            'Arvejas',
        ],
    },
    {
        category: 'Bebidas',
        items: [
            'Gaseosas',
            'Agua Saborizada',
            'Cerveza',
            'Amargo Serrano',
            'Gancia',
            'Fernet',
            'Vinos',
        ],
    },
    {
        category: 'Copetin',
        items: ['Papitas Palitos Manies', 'Aceitunas'],
    },
    {
        category: 'Panaderia',
        items: ['Pan', 'Pan Lactal', 'Facturas', 'Bizcochos', 'Pan Rallado', 'Grisines'],
    },
    {
        category: 'Verduleria',
        items: [
            'Huevos',
            'Pap',
            'Cebolla / Verdeo',
            'Ajo',
            'Ensaladas',
            'Tomate',
            'Zanahoria',
            'Zuchini',
            'Batata',
            'Frutas',
            'Puchero',
        ],
    },
    {
        category: 'Lacteos',
        items: [
            'Leche',
            'Yogurth',
            'Postres',
            'Manteca',
            'Margarina',
            'Crema De Leche',
            'Queso Rallado',
            'Queso Crema',
        ],
    },
    {
        category: 'Fiambres',
        items: [
            'Jamon',
            'Queso',
            'Crudo / Bondiola',
            'Queso Cremoso',
            'Queso Pategras',
            'Roquefort',
            'Ricota',
            'Aceitunas',
            'Salame',
            'Dulce Batata Membrillo',
        ],
    },
    {
        category: 'Pastas Frescas',
        items: ['Discos De Tarta', 'Empanadas', 'Panqueques'],
    },
    {
        category: 'Carnicería',
        items: ['Carne De Vaca', 'Pollo', 'Cerdo'],
    },
];
